name: No-IP Auto Renew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  noip-renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: docker build -t local-noip-renewer .

      - name: Run No-IP Renewer
        env:
          USER: ${{ secrets.NO_IP_USERNAME }}
          PASS: ${{ secrets.NO_IP_PASSWORD }}
          TOTP: ${{ secrets.NO_IP_TOTP_KEY }}
        run: |
          docker run --rm \
            -e NO_IP_USERNAME="$USER" \
            -e NO_IP_PASSWORD="$PASS" \
            -e NO_IP_TOTP_KEY="$TOTP" \
            local-noip-renewer
