name: No-IP Auto Renew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  noip-renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: docker build -t local-noip-renewer .

      - name: Run No-IP Renewer
        run: |
          docker run --rm \
            -e NO_IP_USERNAME="${{ secrets.NO_IP_USERNAME }}" \
            -e NO_IP_PASSWORD="${{ secrets.NO_IP_PASSWORD }}" \
            local-noip-renewer
